name: Apply diff from artifact
inputs:
  diff-artifact-id:
    required: true
    description: Github artifact ID containing a "diff.patch" file in "git diff" format

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.diff-artifact-id }}" ]; then
          echo "::error ::diff-artifact-id is empty"
          exit 1
        fi
    - name: Download diff
      uses: actions/download-artifact@v4
      with:
        artifact-ids: ${{ inputs.diff-artifact-id }}
    - name: Apply diff
      shell: bash
      run: |
        if [ ! -f diff.patch ]; then
          echo "::error ::diff.patch not found!"
          exit 1
        fi
        git apply diff.patch
        rm -f diff.patch