name: updpkgsums and .SRCINFO
inputs:
  pkgname:
    description: Package name
    required: true
  new-pkgver:
    description: New pkgver
    required: false
  new-pkgrel:
    description: New pkgrel
    required: false
  skip-makepkg:
    description: |
      Skip makepkg, commit after updating PKGBUILD.
      Useful for large packages that can't be built on Github, like firefox-vaapi.
    default: 'no'

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.pkgname }}" ]; then
          echo "::error ::pkgname is empty"
          exit 1
        fi
        if [ ! -d "${{ inputs.pkgname }}" ]; then
          echo "::error ::package ${{ inputs.pkgname }} does not exist"
          exit 1
        fi

        if [ -z "${{ inputs.new-pkgver }}" ] && [ -z "${{ inputs.new-pkgrel }}" ]; then
          echo "::error ::new-pkgver and new-pkgrel both empty"
          exit 1
        fi

        if [ ! -z "${{ inputs.new-pkgver }}" ]; then
          valid=$(printf "${{ inputs.new-pkgver }}" | awk 'match($0, "^([a-zA-Z0-9_.]+)$", arr) {print arr[1]}')
          if [ -z "$valid" ]]; then
            echo "::error ::pkgver can only contain letters, numbers, dots and underscores"
            exit 1
          fi
        fi
    - name: "Update checksums & .SRCINFO"
      id: updpkgsums
      uses: dcelasun/archlinux-package-action@0c8508726937a24dc43c01cac5c7c15a09cdc2eb # 25-May-2025
      with:
        path: ${{ inputs.pkgname }}
        updpkgsums: true
        srcinfo: true
        namcap: false
        pkgver: '${{ inputs.new-pkgver }}'
        pkgrel: '${{ inputs.new-pkgrel }}'
        flags: ${{ inputs.skip-makepkg == 'no' && '-cfs --noconfirm' || '' }}
