name: Prepare commit message
inputs:
  pkgname:
    description: Package name
    required: true
  new-pkgver:
    description: New pkgver
    required: false
  new-pkgrel:
    description: New pkgrel
    required: false
  skip-ci:
    description: "Add [skip-ci] to the commit message"
    default: 'yes'

outputs:
  commit-msg:
    description: Commit message
    value: ${{ steps.prep.outputs.commit_msg }}
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.pkgname }}" ]; then
          echo "::error ::pkgname is empty"
          exit 1
        fi
        if [ ! -d "${{ inputs.pkgname }}" ]; then
          echo "::error ::package ${{ inputs.pkgname }} does not exist"
          exit 1
        fi

        if [ -z "${{ inputs.new-pkgver }}" ] && [ -z "${{ inputs.new-pkgrel }}" ]; then
          echo "::error ::new-pkgver and new-pkgrel both empty"
          exit 1
        fi

        if [ ! -z "${{ inputs.new-pkgver }}" ]; then
          valid=$(printf "${{ inputs.new-pkgver }}" | awk 'match($0, "^([a-zA-Z0-9_.]+)$", arr) {print arr[1]}')
          if [ -z "$valid" ]; then
            echo "::error ::pkgver can only contain letters, numbers, dots and underscores"
            exit 1
          fi
        fi
    - name: Prepare commit message
      id: prep
      shell: bash
      run: |
        pkgname="${{ inputs.pkgname }}"
        msg="Update to ${{ inputs.new-pkgver }}"
        if [ -z "${{ inputs.new-pkgver }}" ]; then
          msg="Bump pkgrel to ${{ inputs.new-pkgrel }}"
        fi
        msg="$(printf "[$pkgname] ${msg}")"
        if [ "${{ inputs.skip-ci }}" != 'no' ]; then
          msg="$(printf "$msg\n\n[skip ci]")"
        fi

        # This ugliness is necessary to escape square brackets within the message
        # See comments of https://stackoverflow.com/a/74232400/879047
        echo "commit_msg<<EOF"$'\n'"$msg"$'\n'EOF >> $GITHUB_OUTPUT