name: Push any package
run-name: Push latest ${{ inputs.pkgname }} to AUR
on:
  workflow_dispatch:
    inputs:
      pkgname:
        type: string
        required: true
        description: "Package name"

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          ssh-key: ${{ secrets.SSH_KEY_PRIVATE }}
      - name: Calculate pkgver and pkgrel
        id: pkg
        run: |
          pkgver=$(awk 'match($0, "^pkgver=([a-zA-Z0-9_.]+)$", arr) {print arr[1]}' ${{ inputs.pkgname }}/PKGBUILD)
          pkgrel=$(awk 'match($0, "^pkgrel=([0-9]+)$", arr) {print arr[1]}' ${{ inputs.pkgname }}/PKGBUILD)
          echo "new_pkgver=$pkgver" >> $GITHUB_OUTPUT
          echo "new_pkgrel=$pkgrel" >> $GITHUB_OUTPUT
      - name: Prepare commit message
        uses: ./.github/actions/prepare-commit-msg
        id: prep
        with:
          pkgname: ${{ inputs.pkgname }}
          new-pkgver: ${{ steps.pkg.outputs.new_pkgver }}
          new-pkgrel: ${{ steps.pkg.outputs.new_pkgrel }}
      - name: Push to AUR
        uses: ./.github/actions/push
        with:
          pkgname: ${{ inputs.pkgname }}
          commit-msg: ${{ steps.prep.outputs.commit-msg }}
          new-pkgver: ${{ steps.pkg.outputs.new_pkgver }}
          new-pkgrel: ${{ steps.pkg.outputs.new_pkgrel }}