name: Push any package
run-name: Push latest ${{ inputs.pkgname }} to AUR
on:
  workflow_dispatch:
    inputs:
      pkgname:
        type: string
        required: true
        description: "Package name"

jobs:
  setup:
    # See link for why this is needed
    # https://github.com/orgs/community/discussions/26671#discussioncomment-3252793
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      new_pkgver: ${{ steps.pkg.outputs.new_pkgver }}
      new_pkgrel: ${{ steps.pkg.outputs.new_pkgrel }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          ssh-key: ${{ secrets.SSH_KEY_PRIVATE }}
      - name: Calculate pkgver and pkgrel
        id: pkg
        run: |
          pkgver=$(awk 'match($0, "^pkgver=([0-9]+)$", arr) {print arr[1]}' ${{ inputs.pkgname }}/PKGBUILD)
          pkgrel=$(awk 'match($0, "^pkgrel=([0-9]+)$", arr) {print arr[1]}' ${{ inputs.pkgname }}/PKGBUILD)
          echo "new_pkgver=$pkgver" >> $GITHUB_OUTPUT
          echo "new_pkgrel=$pkgrel" >> $GITHUB_OUTPUT
  update:
    name: Push package
    needs: setup
    uses: ./.github/workflows/update-package.yml
    secrets: inherit
    with:
      pkgname: ${{ inputs.pkgname }}
      new-pkgver: ${{ needs.setup.outputs.new_pkgver }}
      new-pkgrel: ${{ needs.setup.outputs.new_pkgrel }}
      publish-to-aur: 'yes'
      skip-makepkg: 'yes'
